<a href="https://colab.research.google.com/github/jenny102292/data-science-bootcamp/blob/main/01_wprowadzenie/01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### NumPy
>Strona biblioteki: [https://numpy.org/](https://numpy.org/)  
>Dokumentacja: [https://numpy.org/doc/](https://numpy.org/doc/)  
>
>Podstawowa biblioteka do obliczeń numerycznych w języku Python.
>
>Aby zainstalować bibliotekę NumPy, użyj polecenia poniżej:
```
pip install numpy
```

### Spis treści:
1. [Podstawy](#a1)
2. [Typy danych](#a2)
3. [Tworzenie tablic](#a3)
4. [Podstawowe operacje na tablicach](#a4)
5. [Generowanie liczb pseudolosowych](#a5)
6. [Podstawowe funkcje](#a6)
7. [Indeksowanie, Wycinanie](#a7)
8. [Iteracja po tablicach](#a8)
9. [Zmiana rozmiaru tablic](#a9)
10. [Maski logiczne](#a10)

### <a name='a1'></a> Podstawy

In [1]:
import numpy as np
np.__version__

'1.26.4'

In [3]:
print(dir(np))

['ALLOW_THREADS', 'BUFSIZE', 'CLIP', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_builtins', '_distributor_init', '_financial_names', '_get_promotion_state', '_globals', '_int_extended_ms

In [4]:
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        ``__array__`` method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array. If not given, NumPy will try to use
        a default ``dtype`` that can represent the values (by applying promotion
        rules when necessary.)
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if ``__array__`` returns a copy, if obj is a nested
        sequence, or if a copy is needed to satisfy any of the other
        requirements (``dtype``, ``order``, e

1D Array

In [5]:
x = np.array([1, 3])
x

array([1, 3])

In [6]:
print(x)

[1 3]


In [7]:
type(x)

numpy.ndarray

In [8]:
x.ndim

1

In [9]:
x.shape

(2,)

In [10]:
x.size

2

In [11]:
x.dtype

dtype('int64')

In [13]:
x = np.array([1.3, 2.3, 1.4])
print(x)

[1.3 2.3 1.4]


In [14]:
x.dtype

dtype('float64')

2D Array

In [17]:
x = np.array([[1, 2], [-3, 1]])
x

array([[ 1,  2],
       [-3,  1]])

In [18]:
x.ndim

2

In [19]:
x.shape

(2, 2)

In [20]:
x = np.array([[1, 2, 4], [4, 2, 1]])
print(x)

[[1 2 4]
 [4 2 1]]


In [21]:
x.shape

(2, 3)

3D Array

In [25]:
x = np.array(
    [[[4, 3, 1],
      [3, 1, 2]],

     [[4, 1, 3],
      [4, 2, 1]],

     [[3, 2, 1],
      [4, 3, 2]]]
)
x

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]],

       [[3, 2, 1],
        [4, 3, 2]]])

In [26]:
x.ndim

3

In [27]:
x.shape

(3, 2, 3)

### <a name='a2'></a> Typy danych

In [28]:
A = np.array([1, 2, 3])
A.dtype

dtype('int64')

In [29]:
A = np.array([1.0, 2.3, 3.3])
A.dtype

dtype('float64')

In [31]:
A = np.array([1, 2, 3], dtype='float')
A

array([1., 2., 3.])

In [33]:
A = np.array([1, 2, 3], dtype='complex')
A.dtype

dtype('complex128')

In [34]:
A

array([1.+0.j, 2.+0.j, 3.+0.j])

In [37]:
A = np.array([1.0, 2.7, 3.3], dtype='int')
A.dtype

dtype('int64')

In [38]:
A

array([1, 2, 3])

In [39]:
A = np.array([True, False])
A.dtype

dtype('bool')

In [43]:
A = np.array([24, 120, 230]).astype(dtype=np.int8)
A.dtype

dtype('int8')

In [45]:
A = np.array([24, 120, 230]).astype(dtype=np.uint8)
A.dtype

dtype('uint8')

### <a name='a3'></a> Tworzenie tablic

In [46]:
np.zeros(shape=(4, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [47]:
np.zeros(shape=(4, 10), dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [48]:
np.ones(shape=(5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [49]:
np.ones(shape=(5, 5), dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [50]:
np.full(shape=(3, 3), fill_value=4, dtype='int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [51]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
np.arange(start=5, stop=10)

array([5, 6, 7, 8, 9])

In [53]:
np.arange(start=10, stop=100, step=10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [54]:
np.arange(start=100, stop=10, step=-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [55]:
np.arange(start=0, stop=1, step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [57]:
np.linspace(start=0, stop=1, num=11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [59]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [60]:
A.reshape((3, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [61]:
A.reshape((3, -1))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [62]:
A.reshape((-1, 3))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

### <a name='a4'></a> Podstawowe operacje na tablicach

In [64]:
A = np.array([3, 1, 4, 2])
B = np.array([3, -1, 3, 2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [65]:
A + B

array([6, 0, 7, 4])

In [66]:
A - B

array([0, 2, 1, 0])

In [67]:
A * B

array([ 9, -1, 12,  4])

In [68]:
A / B

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [72]:
np.add(A, B)

array([6, 0, 7, 4])

In [73]:
np.subtract(A, B)

array([0, 2, 1, 0])

In [74]:
np.multiply(A, B)

array([ 9, -1, 12,  4])

In [75]:
np.divide(A, B)

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [69]:
A + 3

array([6, 4, 7, 5])

In [70]:
2 * A

array([6, 2, 8, 4])

In [71]:
A + 3 * B

array([12, -2, 13,  8])

In [77]:
X = np.array([[1, 3], [-2, 0]])
Y = np.array([[6, 0], [-1, 2]])
print(X, '\n')
print(Y)

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]]


In [78]:
X * Y

array([[6, 0],
       [2, 0]])

In [79]:
np.dot(X, Y)

array([[  3,   6],
       [-12,   0]])

In [80]:
X.dot(Y)

array([[  3,   6],
       [-12,   0]])

In [81]:
Y.dot(X)

array([[ 6, 18],
       [-5, -3]])

In [82]:
X @ Y

array([[  3,   6],
       [-12,   0]])

### <a name='a5'></a> Generowanie liczb pseudolosowych

In [ ]:
np.random.seed(0)

In [83]:
np.random.randn()

0.17000900804299532

In [84]:
np.random.randn(10)

array([-1.18689063, -0.30172723,  0.44773814,  1.40218656,  0.66852442,
       -0.29074859, -0.60318104, -0.13463545, -2.02055016,  1.01704504])

In [85]:
np.random.randn(10, 4)

array([[-0.54759737, -0.02705956,  0.50764107,  0.08703011],
       [ 0.85614651,  1.93353408, -0.32341109,  0.05361568],
       [-0.01457002, -0.46379926,  0.29452569, -1.61228888],
       [-0.45504526,  1.04684199,  0.75929592,  0.79490576],
       [-0.72247834, -0.04850855, -0.26361604,  0.92840213],
       [ 3.08431274, -0.22350394, -1.44353718,  0.91734641],
       [ 1.39844604,  0.05309181,  1.10422465, -0.5730834 ],
       [ 0.96044054,  1.15240249, -1.14626115, -0.02437669],
       [-2.08647069, -0.11875659,  0.51838544,  0.62069192],
       [ 0.94360202, -1.87383263,  0.38600484, -1.68173725]])

In [86]:
np.random.rand()

0.9786357232297697

In [87]:
np.random.rand(10)

array([0.28335251, 0.1745071 , 0.15117921, 0.74028647, 0.90790154,
       0.03367389, 0.75178968, 0.52739349, 0.86348834, 0.0824645 ])

In [88]:
np.random.rand(10, 2)

array([[0.04859803, 0.90920807],
       [0.72898281, 0.82532662],
       [0.37291079, 0.45651056],
       [0.927867  , 0.62409418],
       [0.86542264, 0.22570052],
       [0.56066865, 0.9275433 ],
       [0.13328064, 0.61830729],
       [0.43850609, 0.79728652],
       [0.31789678, 0.07296865],
       [0.13177978, 0.02428311]])

In [89]:
np.random.randint(10)

1

In [90]:
np.random.randint(low=10, high=101)

99

In [91]:
np.random.randint(low=10, high=101, size=10)

array([ 14,  86,  86,  62,  15,  36,  62,  71, 100,  27])

In [94]:
np.random.choice([4, 2, 1, 3, 5])

4

In [95]:
np.random.choice(['python', 'java', 'sql'])

'python'

In [96]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [98]:
np.random.shuffle(data)
data

array([4, 0, 8, 5, 2, 9, 6, 7, 1, 3])

### <a name='a6'></a> Podstawowe funkcje

In [99]:
np.exp(1)

2.718281828459045

In [100]:
np.sqrt(9)

3.0

In [101]:
np.all([2, 3, 1])

True

In [103]:
np.any([0, 0, 0])

False

In [105]:
bool(1.3)

True

In [106]:
A = np.random.rand(5)
A

array([0.73448674, 0.22947988, 0.32139576, 0.52487168, 0.58461535])

In [107]:
np.argmax(A)

0

In [108]:
A[np.argmax(A)]

0.7344867414081252

In [109]:
np.argmin(A)

1

In [110]:
np.argsort(A)

array([1, 2, 3, 4, 0])

In [111]:
np.max(A)

0.7344867414081252

In [112]:
np.min(A)

0.2294798847457037

In [113]:
np.median(A)

0.5248716780411898

In [114]:
np.mean(A)

0.47896988237712923

In [115]:
np.std(A)

0.18200641074360444

### <a name='a7'></a> Indeksowanie, wycinanie

In [117]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
# A[idx], A[start:stop], A[:stop], A[Start:]

In [118]:
A[2]

2

In [119]:
A[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [120]:
A[:2]

array([0, 1])

In [121]:
A[[0, 2]]

array([0, 2])

In [122]:
A[-1]

19

In [123]:
A[10:15]

array([10, 11, 12, 13, 14])

In [125]:
A = A.reshape(4, 5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [126]:
A[0] #wycinamy wiersz

array([0, 1, 2, 3, 4])

In [128]:
A[:, -2] #wycinamy kolumne

array([ 3,  8, 13, 18])

In [129]:
A[1, 1]

6

In [130]:
A[1, 3]

8

In [132]:
A[1:3, 1:4] #wycinamy czesc tablicy

array([[ 6,  7,  8],
       [11, 12, 13]])

In [134]:
A[1, 2] = 14
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

### <a name='a8'></a> Iteracja po tablicach

In [135]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [136]:
for row in A:
  print(row)

[0 1 2 3 4]
[ 5  6 14  8  9]
[10 11 12 13 14]
[15 16 17 18 19]


In [138]:
for row in A:
  print(row[:3])

[0 1 2]
[ 5  6 14]
[10 11 12]
[15 16 17]


In [139]:
for item in A.flat:
  print(item)

0
1
2
3
4
5
6
14
8
9
10
11
12
13
14
15
16
17
18
19


### <a name='a9'></a> Zmiana rozmiaru tablic

In [140]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [141]:
A.shape

(4, 5)

In [142]:
A.reshape(5, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6, 14],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [143]:
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6, 14,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [144]:
A.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2, 14, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

### <a name='a10'></a> Maski logiczne

In [149]:
A = np.arange(start=-10, stop=10, step=0.5)
A = A.reshape(10, -1)
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [150]:
A > 0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [151]:
A[A > 0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [152]:
np.bitwise_and(A > -5, A < 5)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [153]:
A[np.bitwise_and(A > -5, A < 5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [154]:
np.bitwise_or(A < -5, A > 5)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])