<a href="https://colab.research.google.com/github/jenny102292/data-science-bootcamp/blob/main/07_uczenie-glebokie/02_keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Tensorflow
>Strona biblioteki: [https://www.tensorflow.org/](https://www.tensorflow.org/)  
>Dokumentacja: [https://www.tensorflow.org/api_docs](https://www.tensorflow.org/api_docs)  
>
>Szybko rozwijająca się biblioteka do uczenia maszynowego i uczenia głębokiego rozwijana przez Google.
>
>Aby zainstalować bibliotekę tensorflow, użyj polecenia poniżej:
```
pip install tensorflow
```

### Keras
>Strona biblioteki: [https://keras.io/](https://keras.io/)  
>
>Wysokopoziomowy interfejs do budowy sieci neuronowych. Działa zarówno na Tensorflow, Theano oraz CNTK.
>
>Aby zainstalować bibliotekę keras, użyj polecenia poniżej:
```
pip install keras
```

### Model sekwencyjny (Sequential Model):

1. [Wprowadzenie - pierwszy model](#a1)
2. [Funkcje aktywacji](#a2)
3. [Kompilacja modelu](#a3)
4. [Trenowanie modelu](#a4)
5. [Przykład - klasyfikacja binarna](#a5)
6. [Przykład - klasyfikacja wieloklasowa](#a6)
7. [Przykład - regresja](#a7)

Załadowanie biblioteki tensorflow

In [1]:
%tensorflow_version 2.x
import tensorflow as tf
import numpy as np
import pandas as pd
import plotly.express as px
tf.__version__

Colab only includes TensorFlow 2.x; %tensorflow_version has no effect.


'2.18.0'

### <a name='a1'></a> Wprowadzenie - pierwszy model

Model sekwencyjny to nic innego jak liniowy stos warstw.

In [2]:
# utworzenie instancji klasy Sequential
from tensorflow.keras.models import Sequential

model = Sequential()
print(model)

<Sequential name=sequential, built=False>


Podstawowym elementem składowym modelu są warstwy. Aby dodać najbardziej standardową warstwę - warstwę gęsto połączoną należy użyć warstwy **Dense**. Aby dodać warstwę do modelu należy użyć metody *.add()*

In [3]:
from tensorflow.keras.layers import Dense

model.add(Dense(units=4, input_shape=(10,)))

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Wyświetlenie podsumowania modelu: metoda *.summary()*

In [4]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 4)                   │              44 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 44 (176.00 B)

 Trainable params: 44 (176.00 B)

 Non-trainable params: 0 (0.00 B)

Dodanie kolejnej warstwy

In [5]:
model.add(Dense(units=2))

model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 4)                   │              44 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 2)                   │              10 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 54 (216.00 B)

 Trainable params: 54 (216.00 B)

 Non-trainable params: 0 (0.00 B)

### <a name='a2'></a> Funkcje aktywacji

Istotnym elementem sieci neuronowych jest dobór odpowiednich funkcji aktywacji. Funkcje aktywacji jak sama nazwa wskazuje są odpowiedzialne za aktywowanie odpowiednich neuronów podczas procesu uczenia.

Jeżeli nie określimy podczas dodawania warstwy funkcji aktywacji, domyślnie stosowana jest liniowa funkcja  aktywacji, tzn. $a(x)=x$

Warstwa z liniową funkcją aktywacji może uczyć się nie tylko liniowych przekształceń danych wejściowych. Dlatego stosuje się różne funkcje aktywacji aby rozwiązywać problemy nieliniowe.

[Keras: Funkcje aktywacji](https://keras.io/activations/)

In [6]:
from tensorflow.keras.activations import linear

random_data = np.linspace(start=-3, stop=3, num=300)
data = pd.DataFrame({'data': random_data, 'linear': linear(random_data)})
data.head()

data    linear
0 -3.000000 -3.000000
1 -2.979933 -2.979933
2 -2.959866 -2.959866
3 -2.939799 -2.939799
4 -2.919732 -2.919732

In [7]:
px.line(data, x='data', y='linear', width=500, height=400, range_y=[-3, 3])

In [8]:
from tensorflow.keras.activations import sigmoid

data = pd.DataFrame({'data': random_data, 'sigmoid': sigmoid(random_data)})
data.head()

data   sigmoid
0 -3.000000  0.047426
1 -2.979933  0.048341
2 -2.959866  0.049272
3 -2.939799  0.050221
4 -2.919732  0.051187

In [10]:
px.line(data, x='data', y='sigmoid', width=500, height=400, range_y=[-0.5, 1.5])

In [11]:
from tensorflow.keras.activations import relu

data = pd.DataFrame({'data': random_data, 'relu': relu(random_data)})
data.head()

data  relu
0 -3.000000   0.0
1 -2.979933   0.0
2 -2.959866   0.0
3 -2.939799   0.0
4 -2.919732   0.0

In [12]:
px.line(data, x='data', y='relu', width=500, height=400, range_y=[-0.5, 1.5])

In [13]:
from tensorflow.keras.activations import tanh

data = pd.DataFrame({'data': random_data, 'tanh': tanh(random_data)})
data.head()

data      tanh
0 -3.000000 -0.995055
1 -2.979933 -0.994853
2 -2.959866 -0.994643
3 -2.939799 -0.994424
4 -2.919732 -0.994196

In [14]:
px.line(data, x='data', y='tanh', width=500, height=400, range_y=[-1.5, 1.5])

In [15]:
model = Sequential()
model.add(Dense(units=8,activation='relu', input_shape=(10,)))
model.add(Dense(units=1, activation='sigmoid'))
model.summary()

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning:

Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.



Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_2 (Dense)                      │ (None, 8)                   │              88 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_3 (Dense)                      │ (None, 1)                   │               9 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 97 (388.00 B)

 Trainable params: 97 (388.00 B)

 Non-trainable params: 0 (0.00 B)

### <a name='a3'></a> Kompilacja modelu

Przed rozpoczęciem trenowania sieci należy odpowiednio skonfigurować proces uczenia. W tym kroku określamy:
- rodzaj optymailzatora ([Keras - Optymalizatory](https://keras.io/optimizers/))
- funkcję stray ([Keras - Funkcje Straty](https://keras.io/losses/))
- metryki, które będziemy obserwować podczas trenowania sieci ([Keras - Metryki ](https://keras.io/metrics/))

In [ ]:
# klasyfikacja binarna
model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

# klasyfikacja wieloklasowa
model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

#regresja
model.compile(optimizer='rmsprop',
              loss='mse')

### <a name='a4'></a> Trenowanie modelu

Za dane wejściowe do modelu należy przekazać Numpy arrays:
- **epochs** - krotność przejścia danych przez sieć w procesie uczenia
- **batch_size** - rozmiar wsadu po którym następuje aktualizacja wag
- **validation_split** - część danych treningowych, które zostaną wykorzystane jako zbiór walidacyjny
- **validation_data** - (x_val, y_val) - dane wykorzystane do walidacji modelu

In [ ]:
# model.fit(data, labels, epochs=10, batch_size=32)
# model.fit(data, labels, epochs=10, batch_size=32, validation_split=0.2)
# model.fit(data, labels, epochs=10, batch_size=32, validation_data=(x_val, y_val))

### <a name='a5'></a> Przykład - klasyfikacja binarna

In [16]:
data = np.random.randn(10000, 150)
labels = np.random.randint(2, size=(10000, 1))

print(data.shape)
print(labels.shape)

(10000, 150)
(10000, 1)


In [17]:
data[:3]

array([[-2.52609447, -0.66768275, -0.4124507 ,  1.63749484, -0.83487516,
        -0.28664543, -0.98587648,  0.40452178,  0.47971639, -1.26382545,
         0.45689847,  0.18289108, -0.61768319, -1.25735541, -0.05781293,
         1.69101314,  0.94448206,  0.92003928, -1.87296104, -0.83995709,
        -1.1064152 , -0.44952452, -0.30183165,  1.62456896, -1.4945842 ,
         1.76306791, -0.16933358, -0.64075405, -0.61965339,  0.0288021 ,
        -0.66135276,  1.2282281 ,  0.94145553,  0.88423836, -1.38734603,
         0.86382729, -0.96675132, -0.38344451, -0.48783923,  0.5645216 ,
        -0.49303914, -0.42224333, -0.39020072, -0.93844568,  0.32175063,
         1.00927333, -0.35774767, -0.09708066,  0.37112428, -0.73794475,
        -1.72643873, -0.04991744, -1.06041714,  0.46400128,  0.01034688,
        -0.3282743 , -0.88553824,  0.94265549,  0.77197376,  1.90080309,
         0.13620367, -0.67664387,  0.90015381, -1.01509261, -0.60535512,
        -0.29293804, -1.0247083 , -0.87549629,  0.4

In [18]:
labels[:10]

array([[0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0]])

In [19]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, epochs=20)

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning:

Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.



Epoch 1/20
313/313 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - accuracy: 0.5073 - loss: 0.7823
Epoch 2/20
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5556 - loss: 0.6928
Epoch 3/20
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5733 - loss: 0.6753
Epoch 4/20
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6150 - loss: 0.6545
Epoch 5/20
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6350 - loss: 0.6402
Epoch 6/20
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6590 - loss: 0.6260
Epoch 7/20
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6828 - loss: 0.6084
Epoch 8/20
313/313 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - accuracy: 0.6874 - loss: 0.5956
Epoch 9/20
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7154 - loss: 0.5777
Epoch 10/20
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7229 - loss: 0.5631
Epoch 11/20
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.7359 - loss: 0.5499
Epoch 12/20
313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step

In [21]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, epochs=20, batch_size=64)

Epoch 1/20


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning:

Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.



157/157 ━━━━━━━━━━━━━━━━━━━━ 4s 7ms/step - accuracy: 0.5075 - loss: 0.7951
Epoch 2/20
157/157 ━━━━━━━━━━━━━━━━━━━━ 1s 7ms/step - accuracy: 0.5420 - loss: 0.7003
Epoch 3/20
157/157 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5648 - loss: 0.6805
Epoch 4/20
157/157 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5943 - loss: 0.6650
Epoch 5/20
157/157 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6108 - loss: 0.6582
Epoch 6/20
157/157 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6239 - loss: 0.6497
Epoch 7/20
157/157 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6364 - loss: 0.6413
Epoch 8/20
157/157 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6541 - loss: 0.6243
Epoch 9/20
157/157 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6733 - loss: 0.6137
Epoch 10/20
157/157 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6798 - loss: 0.6052
Epoch 11/20
157/157 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6877 - loss: 0.5960
Epoch 12/20
157/157 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy

In [22]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, epochs=20, batch_size=32, validation_split=0.2)

Epoch 1/20


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning:

Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.



250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5019 - loss: 0.8106 - val_accuracy: 0.5145 - val_loss: 0.7223
Epoch 2/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.5447 - loss: 0.6986 - val_accuracy: 0.5080 - val_loss: 0.7164
Epoch 3/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.5840 - loss: 0.6718 - val_accuracy: 0.5140 - val_loss: 0.7150
Epoch 4/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.6127 - loss: 0.6549 - val_accuracy: 0.5115 - val_loss: 0.7175
Epoch 5/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6403 - loss: 0.6365 - val_accuracy: 0.5115 - val_loss: 0.7195
Epoch 6/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6549 - loss: 0.6282 - val_accuracy: 0.4960 - val_loss: 0.7270
Epoch 7/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6731 - loss: 0.6148 - val_accuracy: 0.5015 - val_loss: 0.7330
Epoch 8/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6973 - loss: 0.5869 - val_accuracy: 0.5025 - val_

In [23]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

history = model.fit(data, labels, epochs=20, batch_size=32, validation_split=0.2, verbose=0)

In [24]:
metrics = history.history
metrics.keys()

dict_keys(['accuracy', 'loss', 'val_accuracy', 'val_loss'])

In [26]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

history = model.fit(data, labels, epochs=20, batch_size=32, validation_split=0.2, verbose=1)

Epoch 1/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.4910 - loss: 0.8448 - val_accuracy: 0.5075 - val_loss: 0.7302
Epoch 2/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.5386 - loss: 0.7031 - val_accuracy: 0.5015 - val_loss: 0.7243
Epoch 3/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - accuracy: 0.5918 - loss: 0.6704 - val_accuracy: 0.5080 - val_loss: 0.7224
Epoch 4/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.6192 - loss: 0.6546 - val_accuracy: 0.5035 - val_loss: 0.7234
Epoch 5/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6441 - loss: 0.6400 - val_accuracy: 0.5085 - val_loss: 0.7269
Epoch 6/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.6600 - loss: 0.6239 - val_accuracy: 0.5140 - val_loss: 0.7280
Epoch 7/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.6834 - loss: 0.6080 - val_accuracy: 0.5145 - val_loss: 0.7380
Epoch 8/20
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.7030 - loss: 0.5892 - val_accuracy: 0.

In [27]:
test_data = np.random.randn(5, 150)
test_labels = np.random.randint(2, size=(5, 1))

In [32]:
predictions = model.predict(test_data)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step


In [33]:
predicted_classes = np.argmax(predictions, axis=1)
print(predicted_classes)

[0 0 0 0 0]


### <a name='a6'></a> Przykład - klasyfikacja wieloklasowa

In [34]:
data = np.random.random((10000, 150))
labels = np.random.randint(10, size=(10000, 1))

In [35]:
print(data.shape)
print(labels.shape)

(10000, 150)
(10000, 1)


In [36]:
labels[:10]

array([[1],
       [5],
       [7],
       [6],
       [3],
       [1],
       [4],
       [5],
       [3],
       [3]])

In [37]:
from tensorflow.keras.utils import to_categorical
labels = to_categorical(labels, num_classes=10)
labels

array([[0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.]])

In [38]:
labels[1]

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

In [39]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(units=10, activation='softmax'))

model.compile(optimizer='rmsprop',
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(data, labels, batch_size=32, epochs=30, validation_split=0.2)

Epoch 1/30


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning:

Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.



250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.1023 - loss: 0.3727 - val_accuracy: 0.0950 - val_loss: 0.3304
Epoch 2/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.1011 - loss: 0.3289 - val_accuracy: 0.1055 - val_loss: 0.3289
Epoch 3/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.1156 - loss: 0.3275 - val_accuracy: 0.0970 - val_loss: 0.3294
Epoch 4/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.1113 - loss: 0.3265 - val_accuracy: 0.1070 - val_loss: 0.3295
Epoch 5/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.1257 - loss: 0.3252 - val_accuracy: 0.0950 - val_loss: 0.3311
Epoch 6/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.1345 - loss: 0.3240 - val_accuracy: 0.1060 - val_loss: 0.3288
Epoch 7/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.1335 - loss: 0.3237 - val_accuracy: 0.1060 - val_loss: 0.3290
Epoch 8/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.1409 - loss: 0.3232 - val_accuracy: 0.0995 - val_

In [40]:
test_data = np.random.random((10, 150))

model.predict(test_data)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step


array([[0.04274566, 0.10528991, 0.11947394, 0.0594567 , 0.12408888,
        0.08657297, 0.11902761, 0.12120332, 0.15448363, 0.06765743],
       [0.11542362, 0.06392571, 0.09312928, 0.18244691, 0.04811546,
        0.09899788, 0.12253848, 0.09240007, 0.08152176, 0.10150084],
       [0.09783977, 0.08546397, 0.14151508, 0.08784531, 0.09827558,
        0.09220994, 0.11090326, 0.06325945, 0.1427283 , 0.07995941],
       [0.05054444, 0.07838469, 0.10247484, 0.04395145, 0.2136797 ,
        0.17878196, 0.0740898 , 0.04676659, 0.10945423, 0.10187234],
       [0.06136551, 0.08016216, 0.15194319, 0.05816755, 0.07117815,
        0.16032355, 0.02817789, 0.03251018, 0.30442372, 0.05174807],
       [0.19454326, 0.07259975, 0.10894329, 0.09308055, 0.0189092 ,
        0.1844254 , 0.04631444, 0.03555253, 0.19502695, 0.05060455],
       [0.11254112, 0.10758787, 0.07656537, 0.02702616, 0.06797644,
        0.14901772, 0.17707732, 0.05288801, 0.11674755, 0.1125725 ],
       [0.07578678, 0.1614664 , 0.1084612

In [42]:
# model.predict_classes(test_data)

predictions = model.predict(test_data)
predicted_classes = np.argmax(predictions, axis=1)
print(predicted_classes)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step
[8 3 8 4 8 8 6 1 1 6]


### <a name='a7'></a> Przykład - regresja

In [43]:
data = np.random.random((10000, 150))
labels = 50 * np.random.random(10000)

In [44]:
labels[:10]

array([18.61008513, 22.95848599, 31.8333897 , 22.31345861, 14.163641  ,
       37.04546   ,  8.10091443, 46.95139923, 39.04287353, 27.14227763])

In [45]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(units=1))

model.compile(optimizer='rmsprop',
              loss='mse')

model.fit(data, labels, epochs=30, batch_size=32, validation_split=0.2)

Epoch 1/30


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning:

Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.



250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 374.2980 - val_loss: 207.5397
Epoch 2/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 207.8705 - val_loss: 207.6657
Epoch 3/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 202.9043 - val_loss: 208.4863
Epoch 4/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 203.2027 - val_loss: 208.5173
Epoch 5/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 205.8073 - val_loss: 209.8120
Epoch 6/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 201.9391 - val_loss: 208.2303
Epoch 7/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 204.7822 - val_loss: 207.9480
Epoch 8/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 204.1544 - val_loss: 208.3069
Epoch 9/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 206.7506 - val_loss: 211.1236
Epoch 10/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 205.6249 - val_loss: 208.9068
Epoch 11/30
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 204.7332 - val_loss: 208.6474
Epoch 12/30
250/250

In [46]:
model = Sequential()
model.add(Dense(units=32, activation='relu', input_shape=(150,)))
model.add(Dense(units=1))

model.compile(optimizer='rmsprop',
              loss='mae',
              metrics=['mse'])

model.fit(data, labels, epochs=10, batch_size=32, validation_split=0.2)

Epoch 1/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 15.6381 - mse: 363.5711 - val_loss: 12.4222 - val_mse: 207.3556
Epoch 2/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 12.4843 - mse: 207.8570 - val_loss: 12.4225 - val_mse: 207.2332
Epoch 3/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 12.5631 - mse: 209.7071 - val_loss: 12.4333 - val_mse: 207.7661
Epoch 4/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 12.4620 - mse: 208.4142 - val_loss: 12.4311 - val_mse: 207.4994
Epoch 5/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 12.5417 - mse: 209.2929 - val_loss: 12.4563 - val_mse: 208.5382
Epoch 6/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 12.1367 - mse: 200.4540 - val_loss: 12.4553 - val_mse: 208.5121
Epoch 7/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 12.2681 - mse: 204.0773 - val_loss: 12.4631 - val_mse: 208.7096
Epoch 8/10
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 4ms/step - loss: 12.2847 - mse: 203.6480 - val_loss: 12.5017 - val_mse: 210.3772
Epoch 9/

In [47]:
test_data = np.random.random((10, 150))

model.predict(test_data)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step


array([[24.002226],
       [24.67273 ],
       [25.56766 ],
       [24.663706],
       [25.795824],
       [24.874117],
       [25.851673],
       [21.88912 ],
       [25.468622],
       [24.720242]], dtype=float32)